version: 0.0

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on date
  build:
    commands:
      - echo Build phase started on date
      - echo Compiling the static files
      # Jika ada proses build khusus, tambahkan di sini
      - echo Build completed on date
  post_build:
    commands:
      - echo Build completed on date

artifacts:
  files:
    - '*/'
  name: ca-i-$(date +%Y-%m-%d)