version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install for pure HTML
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on date
  build:
    commands:
      - echo Build phase started on date
      - echo Compiling the static files
      # Jika ada proses build khusus, tambahkan di sini.
      - echo Build completed on date
  post_build:
    commands:
      - echo Build completed on date
      - aws s3 sync . s3://s3-codep  --delete

artifacts:
  files:
    - '*/'
  name: ca-i-$(date +%Y-%m-%d)